name: Python Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  syntax:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Compile project
        run: python -m compileall src gerar_imagens_json.py organizar_imagens_json.py
